name: ez_grader
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.7
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/logo.png
  color_dark: "#121212"
  image_dark: assets/logo/logo.png

  android_12:
    image: assets/logo/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo/logo.png
    icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/videos/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
