// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtdnWDuAmIZ8sy4LiHm1K3kT2XOoY7sr8',
    appId: '1:10654351376:web:a1afa79b2e8579053f4a95',
    messagingSenderId: '10654351376',
    projectId: 'ez-grader---dtu',
    authDomain: 'ez-grader---dtu.firebaseapp.com',
    storageBucket: 'ez-grader---dtu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9CFHKWZnZ05fkKFAZYOi-iuXsfbVMpSM',
    appId: '1:10654351376:android:a1aa46f710e148583f4a95',
    messagingSenderId: '10654351376',
    projectId: 'ez-grader---dtu',
    storageBucket: 'ez-grader---dtu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HWx0EAR0Ol1S_APpaToLbnTvCHMM50c',
    appId: '1:10654351376:ios:79ec50a1566ae50a3f4a95',
    messagingSenderId: '10654351376',
    projectId: 'ez-grader---dtu',
    storageBucket: 'ez-grader---dtu.appspot.com',
    iosBundleId: 'com.example.ezGrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2HWx0EAR0Ol1S_APpaToLbnTvCHMM50c',
    appId: '1:10654351376:ios:8c2bc62581e8ad253f4a95',
    messagingSenderId: '10654351376',
    projectId: 'ez-grader---dtu',
    storageBucket: 'ez-grader---dtu.appspot.com',
    iosBundleId: 'com.example.ezGrader.RunnerTests',
  );
}
